### ISSUE TITLE
Multiple platforms match current OS on Window Subsystem for Linux

### ISSUE THREAD

**Issue by jasondamour** [kdeldycke/extra-platforms#158]
```
RuntimeError: Multiple platforms match current OS: [Platform(id='ubuntu', name='Ubuntu', current=True), Platform(id='wsl2', name='Windows Subsystem for Linux v2', current=True)]
```

Ubuntu 22.04 on WSL 2
```
➜  uname -a  
Linux 5.15.167.4-microsoft-standard-WSL2
➜  cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.5 LTS"
```

Coming as a transitive error from `click_extra`:
```
  click-extra==4.11.7
    extra-platforms==1.6.0
```

Similar to this issue: https://github.com/kdeldycke/meta-package-manager/issues/944

**Comment by kdeldycke** [comment]
Good catch! I just fixed the `current_os()` utility method, and added a new `current_platforms()` utility to differentiate the utility usage. Which allowed me to refine detection heuristics.

I'll do a 2.0.0 release of `extra-platforms` to fix the issue.

**Comment by jasondamour** [comment]
@kdeldycke Still waiting on a new release of click_extra for the new dependency constraint to take effect

**Comment by kdeldycke** [comment]
> [@kdeldycke](https://github.com/kdeldycke) Still waiting on a new release of click_extra for the new dependency constraint to take effect

Oh ok I missed that part! 😅 I'll release a new version of Click Extra in a couple of hours then.

**Comment by kdeldycke** [comment]
Done: https://pypi.org/project/click-extra/4.12.0/

**Comment by jasondamour** [comment]
Thanks @kdeldycke, appreciate the responsiveness as always
